version: '3.5'

services:
  postgres:
    image: 'postgres:bullseye'
    container_name: 'java-postgres'
#    скрыть при необходимости (открыл для мониторинга через dbeaver)
    ports:
      - '5432:5432'
    environment:
      - 'POSTGRES_PASSWORD=root'
      - 'POSTGRES_USER=admin'
      - 'POSTGRES_DB=productmonitoring'

  app:
    build: ./
    container_name: 'java-app'
    ports:
      - '8080:8080'
    environment:
      - 'SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/productmonitoring?serverTimezone=UTC'

