#поднять только postgres для сборки jar и запука приложения вне контейнера
version: '3.5'

services:
  postgres:
    image: 'postgres:bullseye'
    container_name: 'postgres'
    ports:
      - '5432:5432'
    environment:
      - 'POSTGRES_PASSWORD=root'
      - 'POSTGRES_USER=admin'
      - 'POSTGRES_DB=productmonitoring'

